export const tags = {
    topicTag: "topicTag" as const,
    categoryTag: "categoryTag" as const,
    userTag: "userTag" as const,
    mediaTag: "mediaTag" as const,
    countryTag: "countryTag" as const,
    divisionTag: "divisionTag" as const,
    districtTag: "districtTag" as const,
    upazillaTag: "upazillaTag" as const,
    unionTag: "unionTag" as const,
    contactTag: "contactTag" as const,
    newsTag: "newsTag" as const,
    breakingNewsTag: "breakingNewsTag" as const,
    reporterTag: "reporterTag" as const,
    pollTag: "pollTag" as const,
    categoryPosistionTag: "categoryPosistionTag" as const,
    epaperCategoryTag: "epapercategoryPosistion" as const,
};
